import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');const landing=read('src/landing.ts'),readiness=read('src/readiness.ts'),quickstart=read('src/quickstart.ts'),fleet=read('src/fleet.ts'),integrations=read('src/integrations.ts'),economics=read('src/economics.ts'),trust=read('src/trust.ts'),dataPractices=read('src/data-practices.ts'),index=read('src/index.ts'),adoption=read('src/adoption.ts'),css=read('public/sota.css'),factualCss=read('public/revamp-factual.css'),readinessCss=read('public/readiness.css'),legacyCss=read('public/legacy-readable.css');
test('accessible responsive revamp chrome',()=>{for(const s of [landing,readiness,quickstart,fleet,integrations]){assert.match(s,/class="rv-skip" href="#main-content"/);assert.match(s,/<main id="main-content">/);assert.match(s,/class="rv-mobile-nav"/);assert.match(s,/<summary>Menu<\/summary>/);assert.match(s,/seenrelay-logo\.svg/);assert.match(s,/href="\/sota\.css"/)}assert.match(css,/min-height:44px/)});
test('registered service discovery relations remain machine-readable',()=>{for(const rel of ['service-desc','service-meta','service-doc']){assert.match(index,new RegExp('rel="'+rel+'"'));assert.match(landing,new RegExp('rel="'+rel+'"'))}assert.match(index,/c\.header\('vary', 'Accept'\)/);assert.match(index,/c\.json\(serviceDescriptor\(origin\)\)/)});
test('dynamic robots cannot be shadowed by static asset',()=>{assert.equal(fs.existsSync(new URL('../public/robots.txt',import.meta.url)),false);assert.match(adoption,/Disallow: \/admin/);assert.match(adoption,/Disallow: \/internal/);assert.match(adoption,/Sitemap: \${origin}\/sitemap\.xml/)});
test('readiness headings stay sequential',()=>{assert.doesNotMatch(readiness,/<h4>/);assert.match(readiness,/<h3>Give your coding agent this audit task<\/h3>/)});
test('first viewport states safe boundary',()=>{assert.match(landing,/Reduce repeated AI validation without weakening the authoritative source/);assert.match(landing,/Start with evidence, not installation/);assert.match(landing,/every authoritative call still enabled/i);assert.match(landing,/Native controls win whenever they solve the same problem better/i);assert.match(landing,/no truth verdict/i)});
test('revamp pages keep a practical readability floor',()=>{for(const expected of [/\.rv-nav-links\{font-size:13px\}/,/\.rv-kicker,\.rv-eyebrow\{font-size:12px/,/\.rv-flow-list small\{font-size:13px/,/\.rv-card p\{font-size:14px/,/\.rv-footer\{font-size:12px/,/body\.revamp \.rv-evidence-card footer span\{font-size:12px/])assert.match(css,expected);assert.match(factualCss,/\.rv-evidence-card footer\{[^}]*font:750 12px/);assert.match(readinessCss,/\.readiness-form label\{[^}]*font-size:13px/);assert.match(readinessCss,/\.readiness-small\{[^}]*font-size:13px!important/);assert.match(readinessCss,/\.readiness-status\{[^}]*font:800 12px/);assert.match(readinessCss,/\.readiness-check p\{[^}]*font-size:13px/)});
test('legacy human pages load the readability layer',()=>{for(const page of [economics,trust,dataPractices])assert.match(page,/href="\/legacy-readable\.css"/);assert.match(legacyCss,/body\{font-size:16px\}/);assert.match(legacyCss,/\.eyebrow,\.kicker\{font-size:12px/);assert.match(legacyCss,/\.proof-grid article span[^}]*font-size:13px/);assert.match(legacyCss,/footer\{font-size:12px/);assert.match(legacyCss,/body \.label\{font-size:12px!important/);assert.match(legacyCss,/body \.terminal pre\{font-size:13px!important/)});
