import test from 'node:test';
import assert from 'node:assert/strict';
import { verifyStandardsShadowNaturalLineage, evaluateStandardsShadowGateV3 } from '../scripts/standards-shadow-evidence-gate-v3.mjs';
const A=`sha256:${'a'.repeat(64)}`,B=`sha256:${'b'.repeat(64)}`;
const rec=(n=0,c=false,x={})=>({check_status:'UNKNOWN',policy_reusable:false,reuse_would_match_validation:null,observe_after_baseline:false,baseline_ms:100+n,baseline_cost:0,check_ms:50+n,observe_ms:0,check_cost:0,observe_cost:0,source_native_conditional_available:c,source_native_conditional_attempted:c,...x});
function input(records,extra={}){const c=records.some(r=>r.source_native_conditional_available);return{schema_version:2,workload_id:'standards-watch-daily-v1',workload_class:'structured_source_reads',sample_type:'natural_workload',baseline_definition:'best_existing_non_shared_path',controls:{local_cache:{available:false,measured:false},source_native_conditional:{available:c,measured:c},provider_native_cache:{available:false,measured:false}},provenance_schema_version:2,collection_epoch:'schedule-only-v3',run_event:'schedule',run_id:'1001',parent_run_id:null,records,...extra}}
function bun(b,prev=null,delta=null){const records=b.records,cur=delta??records.length,c=records.slice(-cur).filter(r=>r.source_native_conditional_available).length,prior=prev?.ledger.control_evidence??{validator_available_calls:0,conditional_available_calls:0,conditional_attempts:0,conditional_304_confirmations:0},ce={validator_available_calls:prior.validator_available_calls+c,conditional_available_calls:prior.conditional_available_calls+c,conditional_attempts:prior.conditional_attempts+c,conditional_304_confirmations:prior.conditional_304_confirmations};const p={provenance_schema_version:2,collection_epoch:'schedule-only-v3',sample_type:'natural_workload',run_event:'schedule',run_id:b.run_id,parent_run_id:b.parent_run_id,workload_id:'standards-watch-daily-v1'};return{benchmark:structuredClone(b),summary:{schema_version:2,workload_class:'structured_source_reads',first_party:true,external_adoption_evidence:false,source_count:4,source_native_validator_available_count:c,source_native_conditional_available_count:c,source_native_conditional_attempt_count:c,source_native_conditional_304_count:0,observe_requests_sent:0,current_run_benchmark_records:cur,cumulative_benchmark_records:records.length,preliminary_sample_floor_met:records.length>=100,evaluation_state:'complete',evaluation_reason:null,...p},evaluation:null,state:{schema_version:1,entries:{},raw_values_retained:false,sources_retained:false,...p},ledger:{schema_version:1,workload_class:'structured_source_reads',natural_schedule:'daily',records:structuredClone(records),control_evidence:ce,raw_values_retained:false,fact_identity_retained:false,sources_retained:false,timestamps_retained:false,...p}}}
const opts=b=>({implementationEvidenceFingerprint:A,benchmarkEvidenceFingerprint:B,behaviorProofFingerprint:A,sequentialityProofFingerprint:B,lineageBundles:[bun(b)]});

test('lineage proof verifies v3 and binds exact head benchmark',()=>{const b=input([rec(),rec(1,true)]);const p=verifyStandardsShadowNaturalLineage([bun(b)]);assert.equal(p.verified,true);assert.equal(p.collection_epoch,'schedule-only-v3');assert.match(p.head_benchmark_fingerprint,/^sha256:/);assert.equal(p.final_control_evidence.conditional_available_calls,1);assert.equal(p.interpretation.best_native_per_record_verified_by_harness,true);assert.equal(p.interpretation.behavior_equivalence_verified_by_harness,false)});
test('Gate B verifies lineage itself but keeps behavior and sequentiality blockers',()=>{const b=input([rec(),rec(100)]);const o=evaluateStandardsShadowGateV3(b,opts(b));assert.equal(o.evidence.lineage_proof_verified_by_harness,true);assert.equal(o.evidence.lineage_head_benchmark_fingerprint,o.evidence.benchmark_canonical_fingerprint);assert.equal(o.gate_b.workload_evidence_ready,false);assert.ok(o.gate_b.admission_blockers.includes('behavior_proof_not_verified_by_harness'));assert.ok(o.gate_b.admission_blockers.includes('sequentiality_proof_not_verified_by_harness'));assert.equal(o.gate_b.admission_blockers.some(x=>x.includes('lineage')),false);assert.equal(o.interpretation.optimizer_authorized,false)});
test('exact benchmark mismatch against verified lineage fails closed',()=>{const b=input([rec()]),o=opts(b);b.records[0].check_ms++;assert.throws(()=>evaluateStandardsShadowGateV3(b,o),/lineage head does not match/)});
test('v2, push, and commissioning evidence cannot enter v3 lineage',()=>{for(const [k,v] of [['collection_epoch','schedule-only-v2'],['run_event','push'],['sample_type','commissioning']]){const b=input([rec()]);b[k]=v;const x=bun(input([rec()]));x.benchmark[k]=v;assert.throws(()=>verifyStandardsShadowNaturalLineage([x]))}});
test('per-record native conditional must be attempted whenever available',()=>{const b=input([rec(0,true,{source_native_conditional_attempted:false})]);assert.throws(()=>evaluateStandardsShadowGateV3(b,{implementationEvidenceFingerprint:A,benchmarkEvidenceFingerprint:B,behaviorProofFingerprint:A,sequentialityProofFingerprint:B,lineageBundles:[]}),/must attempt source-native conditional/)});
test('native control availability is decision-time evidence, not validator learned after response',()=>{const b=input([rec()]),x=bun(b);x.summary.source_native_validator_available_count=3;x.ledger.control_evidence.validator_available_calls=3;const p=verifyStandardsShadowNaturalLineage([x]);assert.equal(p.verified,true);assert.equal(x.benchmark.controls.source_native_conditional.available,false);assert.equal(p.final_control_evidence.conditional_available_calls,0)});
test('lineage rejects counter, record, privacy, and continuity tampering',()=>{const r=input([rec(),rec(1,true)]),x=bun(r);x.ledger.control_evidence.conditional_attempts++;assert.throws(()=>verifyStandardsShadowNaturalLineage([x]),/cumulative conditional counters/);const y=bun(r);y.ledger.sources_retained=true;assert.throws(()=>verifyStandardsShadowNaturalLineage([y]),/ledger contract/);const z=bun(r);z.benchmark.records[0].check_ms++;assert.throws(()=>verifyStandardsShadowNaturalLineage([z]),/benchmark\/ledger mismatch/)});
test('two-run lineage enforces parent and append continuity',()=>{const b1=input([rec(),rec(1)]),x=bun(b1);const b2=input([...b1.records,rec(2,true),rec(3,true)],{run_id:'1002',parent_run_id:'1001'}),y=bun(b2,x,2);const p=verifyStandardsShadowNaturalLineage([x,y]);assert.equal(p.run_count,2);assert.equal(p.observed_record_count,4);const bad=structuredClone(y);bad.ledger.records[0].check_ms++;bad.benchmark.records[0].check_ms++;assert.throws(()=>verifyStandardsShadowNaturalLineage([x,bad]),/ledger continuity/)});
test('100 records above 30% are still only conditional candidate',()=>{const b=input(Array.from({length:100},()=>rec()));const o=evaluateStandardsShadowGateV3(b,opts(b));assert.equal(o.gate_b.preliminary_sample_floor_met,true);assert.equal(o.gate_b.conditional_active_prototype_candidate_for_this_workload,true);assert.equal(o.gate_b.active_prototype_candidate_for_this_workload,false);assert.equal(o.interpretation.next_step,'VERIFY_BEHAVIOR_AND_SEQUENTIALITY_PROOFS_AND_TEST_A_SECOND_USEFUL_WORKLOAD')});
test('mature <20% emits kill signal and >50% gross never proves commercial net savings',()=>{let b=input(Array.from({length:100},()=>rec(0,false,{check_ms:10}))),o=evaluateStandardsShadowGateV3(b,opts(b));assert.equal(o.gate_b.marginal_kill_signal_for_this_workload,true);b=input(Array.from({length:100},()=>rec(0,false,{check_ms:120})));o=evaluateStandardsShadowGateV3(b,opts(b));assert.equal(o.gate_b.conditional_improvement_percent>50,true);assert.equal(o.gate_b.commercial_net_savings_evaluable,false);assert.equal(o.gate_b.commercially_compelling_proven,false)});
test('replay is diagnostic-only and requires no lineage',()=>{const b=input(Array.from({length:100},()=>rec()),{sample_type:'replayed'});delete b.provenance_schema_version;delete b.collection_epoch;delete b.run_event;delete b.run_id;delete b.parent_run_id;const o=evaluateStandardsShadowGateV3(b,{implementationEvidenceFingerprint:A,benchmarkEvidenceFingerprint:B,behaviorProofFingerprint:A,sequentialityProofFingerprint:B});assert.equal(o.evidence.lineage_proof_verified_by_harness,false);assert.ok(o.gate_b.admission_blockers.includes('replayed_input_is_diagnostic_only'));assert.equal(o.interpretation.next_step,'REPLAY_DIAGNOSTIC_ONLY_COLLECT_SCHEDULED_NATURAL_EVIDENCE')});
test('nonzero monetary fields and unmeasured available controls fail closed',()=>{let b=input([rec(0,false,{check_cost:.01})]);assert.throws(()=>evaluateStandardsShadowGateV3(b,{implementationEvidenceFingerprint:A,benchmarkEvidenceFingerprint:B,behaviorProofFingerprint:A,sequentialityProofFingerprint:B,lineageBundles:[]}),/zero monetary/);b=input([rec()]);b.controls.source_native_conditional={available:true,measured:false};assert.throws(()=>evaluateStandardsShadowGateV3(b,opts(input([rec()]))),/available but unmeasured/)});
