import test from 'node:test';
import assert from 'node:assert/strict';
import { verifyStandardsShadowExecutionContractV1, evaluateStandardsShadowGateV3Verified } from '../scripts/standards-shadow-execution-proof-v1.mjs';

const B=`sha256:${'b'.repeat(64)}`;
function record(i=0){return{check_status:'UNKNOWN',policy_reusable:false,reuse_would_match_validation:null,observe_after_baseline:false,baseline_ms:100+i,baseline_cost:0,check_ms:50+i,observe_ms:0,check_cost:0,observe_cost:0,source_native_conditional_available:false,source_native_conditional_attempted:false};}
function benchmark(records,runId='1001'){return{schema_version:2,workload_id:'standards-watch-daily-v1',workload_class:'structured_source_reads',sample_type:'natural_workload',baseline_definition:'best_existing_non_shared_path',controls:{local_cache:{available:false,measured:false},source_native_conditional:{available:false,measured:false},provider_native_cache:{available:false,measured:false}},provenance_schema_version:2,collection_epoch:'schedule-only-v3',run_event:'schedule',run_id:runId,parent_run_id:null,records};}
function bundle(b){const p={provenance_schema_version:2,collection_epoch:'schedule-only-v3',sample_type:'natural_workload',run_event:'schedule',run_id:b.run_id,parent_run_id:null,workload_id:'standards-watch-daily-v1'};return{benchmark:structuredClone(b),summary:{schema_version:2,workload_class:'structured_source_reads',first_party:true,external_adoption_evidence:false,source_count:4,source_native_validator_available_count:0,source_native_conditional_available_count:0,source_native_conditional_attempt_count:0,source_native_conditional_304_count:0,observe_requests_sent:0,current_run_benchmark_records:b.records.length,cumulative_benchmark_records:b.records.length,preliminary_sample_floor_met:b.records.length>=100,evaluation_state:'complete',evaluation_reason:null,...p},evaluation:null,state:{schema_version:1,entries:{},raw_values_retained:false,sources_retained:false,...p},ledger:{schema_version:1,workload_class:'structured_source_reads',natural_schedule:'daily',records:structuredClone(b.records),control_evidence:{validator_available_calls:0,conditional_available_calls:0,conditional_attempts:0,conditional_304_confirmations:0},raw_values_retained:false,fact_identity_retained:false,sources_retained:false,timestamps_retained:false,...p}};}

test('verifies behavior independence, real 304 paths, and sequentiality for every CHECK outcome',async()=>{const p=await verifyStandardsShadowExecutionContractV1();assert.equal(p.behavior_equivalence_verified_by_harness,true);assert.equal(p.sequentiality_verified_by_harness,true);assert.equal(p.behavior_cases.length,18);assert.equal(p.behavior_cases.filter(x=>x.conditional_response==='304').length,6);assert.equal(p.sequentiality_cases.length,6);assert.deepEqual(p.sequentiality_cases.map(x=>x.check_mode),['UNKNOWN','SAME_OBSERVED','CHANGED_OBSERVED','CONTESTED','STALE','CHECK_ERROR']);assert.ok(p.sequentiality_cases.every(x=>x.pair_count===4));const a=p.behavior_cases.find(x=>x.check_mode==='UNKNOWN'&&x.conditional_response==='304');const b=p.behavior_cases.find(x=>x.check_mode==='UNKNOWN'&&x.conditional_response==='200'&&x.prior_validator===true);assert.notEqual(a.authoritative_state_fingerprint,b.authoritative_state_fingerprint);assert.equal(p.validation_suppression_observed,false);assert.equal(p.observe_requests_observed,0);assert.match(p.proof_fingerprint,/^sha256:[0-9a-f]{64}$/);});

test('execution verifier rejects injected runners/options',async()=>{let injected=false;await assert.rejects(verifyStandardsShadowExecutionContractV1({runBenchmark:async()=>{injected=true;}}),/accepts no injected runner or options/);assert.equal(injected,false);});

test('verified wrapper removes only execution-contract blockers before sample floor',async()=>{const b=benchmark([record()]);const out=await evaluateStandardsShadowGateV3Verified(b,{benchmarkEvidenceFingerprint:B,lineageBundles:[bundle(b)]});assert.equal(out.evidence.lineage_proof_verified_by_harness,true);assert.equal(out.evidence.behavior_proof_verified_by_harness,true);assert.equal(out.evidence.sequentiality_proof_verified_by_harness,true);assert.equal(out.gate_b.admission_blockers.includes('behavior_proof_not_verified_by_harness'),false);assert.equal(out.gate_b.admission_blockers.includes('sequentiality_proof_not_verified_by_harness'),false);assert.ok(out.gate_b.admission_blockers.includes('natural_sample_floor_not_met'));assert.equal(out.gate_b.workload_evidence_ready,false);assert.equal(out.interpretation.optimizer_authorized,false);});

test('100 mature records may become per-workload evidence-ready but never global or optimizer-authorized',async()=>{const b=benchmark(Array.from({length:100},(_,i)=>record(i%4)));const out=await evaluateStandardsShadowGateV3Verified(b,{benchmarkEvidenceFingerprint:B,lineageBundles:[bundle(b)]});assert.equal(out.gate_b.preliminary_sample_floor_met,true);assert.equal(out.gate_b.above_marginal_floor,true);assert.equal(out.gate_b.admission_blockers.length,0);assert.equal(out.gate_b.workload_evidence_ready,true);assert.equal(out.gate_b.global_gate_pass,false);assert.equal(out.interpretation.shadow_check_bypass_supported_for_this_workload,false);assert.equal(out.interpretation.conditional_bypass_evidence_ready_for_this_workload,true);assert.equal(out.interpretation.optimizer_authorized,false);assert.equal(out.interpretation.attention_microkernel_prototype_authorized,false);});

test('mature sub-20 headroom remains not evidence-ready',async()=>{const b=benchmark(Array.from({length:100},()=>({...record(),check_ms:10})));const out=await evaluateStandardsShadowGateV3Verified(b,{benchmarkEvidenceFingerprint:B,lineageBundles:[bundle(b)]});assert.equal(out.gate_b.marginal_kill_signal_for_this_workload,true);assert.equal(out.gate_b.workload_evidence_ready,false);});

test('verified wrapper ignores caller attempts to inject a runner',async()=>{const b=benchmark([record()]);let injected=false;const out=await evaluateStandardsShadowGateV3Verified(b,{benchmarkEvidenceFingerprint:B,lineageBundles:[bundle(b)],runBenchmark:async()=>{injected=true;throw new Error('must not run');}});assert.equal(injected,false);assert.equal(out.evidence.behavior_proof_verified_by_harness,true);});
