import { dataPracticesDescriptor } from './data-practices.js';
import { siteFooterHtml } from './public-facts-view.js';

function esc(value: unknown): string {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

export function privacyPage(origin: string): string {
  const d = dataPracticesDescriptor(origin);
  const retention = d.retention;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="SeenRelay privacy notice covering the local scanner and hosted CHECK/OBSERVE service."><title>SeenRelay — Privacy Notice</title><link rel="stylesheet" href="/site.css"><link rel="stylesheet" href="/legacy-readable.css"></head><body><header class="nav"><a class="brand" href="/">SeenRelay<span class="pulse"></span></a><nav><a href="/">Overview</a><a href="/data-practices">Data practices</a><a href="/trust">Trust</a></nav></header><main>
<section class="hero compact"><div class="eyebrow">PRIVACY NOTICE</div><h1>Collect only what the validation job needs.</h1><p class="lead">Effective September 25, 2026. This notice explains what SeenRelay processes, why it is processed, how long application data is retained, and which infrastructure providers may process service traffic.</p></section>

<section class="section"><div class="section-head"><div><div class="eyebrow">SCOPE</div><h2>Local scanner and hosted service are different.</h2></div></div><div class="proof-grid"><article><b>Local scanner</b><span><code>npx seenrelay scan</code> reads supported project files locally. It does not contact SeenRelay, upload source code, create an account, or enable reuse.</span></article><article><b>Hosted CHECK / OBSERVE</b><span>Network use is optional. CHECK compares a caller-known value with recent evidence for the same deterministic fact. OBSERVE accepts evidence only after the caller independently obtained it.</span></article><article><b>No account or payment profile</b><span>SeenRelay currently requires no SeenRelay account or API key and billing is disabled.</span></article><article><b>No conversation harvesting</b><span>SeenRelay is not designed to read Claude memory, chat history, conversation summaries, or unrelated user files.</span></article></div></section>

<section class="section"><div class="section-head"><div><div class="eyebrow">APPLICATION DATA</div><h2>What the hosted service processes.</h2></div><p>The hosted service processes only data needed for deterministic fact matching, freshness evidence, abuse controls, and bounded operational measurement.</p></div><div class="proof-grid"><article><b>Fact identity</b><span>Subject, predicate, qualifiers, canonicalized source URL, and optional source-native locator.</span></article><article><b>Observation processing</b><span>The submitted value may exist in request memory long enough to compute a deterministic fingerprint. Active Production stores the fingerprint and bounded evidence metadata rather than another caller's raw submitted value.</span></article><article><b>Pseudonymous provenance</b><span>Observer/client continuity uses privacy-salted identifiers. Raw IP address, raw user-agent, raw Ed25519 public key, and raw self-asserted observer ID are not used as application database identity.</span></article><article><b>Operational metrics</b><span>Aggregate CHECK/OBSERVE outcomes, reuse accounting, lease state, and aggregate MCP protocol-interest events may be measured for reliability, abuse prevention, and product evaluation.</span></article></div><p class="lead small">Do not submit passwords, API keys, access tokens, private cryptographic keys, signed URLs, or unnecessary sensitive personal data.</p></section>

<section class="section"><div class="section-head"><div><div class="eyebrow">PURPOSE</div><h2>Why SeenRelay processes this data.</h2></div></div><p class="lead">The purpose is to operate a validation-reuse service that can compare recent observations without treating them as universal truth, preserve authoritative fallback, prevent unsafe or abusive reuse, and measure whether the service is useful. SeenRelay does not sell personal data and does not use submitted values to train an AI model.</p></section>

<section class="section"><div class="section-head"><div><div class="eyebrow">RETENTION</div><h2>Application retention is bounded where operational state permits.</h2></div></div><div class="metrics"><article><div class="label">Observation evidence</div><div class="metric">${esc(retention.observation_rows_days)}d</div><div class="hint">configured evidence horizon</div></article><article><div class="label">Observer/fact state</div><div class="metric">${esc(retention.observer_fact_state_days)}d</div><div class="hint">aligned pseudonymous state</div></article><article><div class="label">Hive leases</div><div class="metric">${esc(retention.hive_lease_operational_retention_days)}d</div><div class="hint">operational retention</div></article><article><div class="label">Reuse events</div><div class="metric">${esc(retention.useful_reuse_event_retention_days)}d</div><div class="hint">utility evidence</div></article></div><p class="lead small">Fact summaries and aggregate operational measurements may be retained longer where needed for STALE/latest-observed semantics, abuse controls, or historical measurement. Infrastructure-provider backups and security logs follow the providers' own retention practices.</p></section>

<section class="section"><div class="section-head"><div><div class="eyebrow">INFRASTRUCTURE</div><h2>Service providers.</h2></div></div><div class="proof-grid"><article><b>Vercel</b><span>Hosts the web/API runtime and may process network/security/operational data under its terms and privacy notice. <a href="https://vercel.com/legal/privacy-notice">Vercel Privacy Notice</a>.</span></article><article><b>Neon</b><span>Provides PostgreSQL infrastructure for application state and may process service data under its terms and privacy practices. <a href="https://neon.com/privacy-policy">Neon Privacy Policy</a>.</span></article></div></section>

<section class="section"><div class="section-head"><div><div class="eyebrow">CHOICES &amp; CONTACT</div><h2>Use the local path when you do not want hosted processing.</h2></div></div><p class="lead">You can use the local scanner without sending project source to SeenRelay. If you use the hosted service, submit only eligible public or legitimately accessible source-backed facts under your own policy. For product or privacy questions, contact the repository owner through <a href="https://github.com/ovladon">GitHub</a>. Do not post secrets or sensitive personal data in a public issue. For security vulnerabilities, use the repository's private vulnerability-reporting channel described in <a href="https://github.com/ovladon/seenrelay/blob/main/SECURITY.md">SECURITY.md</a>.</p><p class="lead small">Because SeenRelay has no user accounts and application identifiers are pseudonymous, locating data associated with a particular person may require enough information to identify the relevant pseudonymous record without exposing additional sensitive data.</p></section>

<section class="section final"><div><div class="eyebrow">TECHNICAL DETAIL</div><h2>Need the exact application-level fields?</h2></div><div class="cta"><a class="primary" href="/data-practices">Data practices</a><a class="secondary" href="/data-practices.json">Machine JSON</a></div></section>
</main>${siteFooterHtml()}</body></html>`;
}
